target: dependncies
	action

CPP = g++
CPPFLAGS = -lncurses

cs19s23as06: through.o sweat.o steamboat.o stair.o seen.o scream.o reindeer.o if.o hail.o grade.o
	$(CPP) $(CPPFLAGS) -o cs19s23as06 through.o seat.o steamboat.o stair.o seen.o scream.o reindeer.o if.o hail.o grade.o

through.o: through.cpp squeak.h service.h school.h teeth.h
	$(CPP) $(CPPFLAGS) -c through.cpp

seat.o: sweat.cpp ax.h goldfish.h squak.h
	$(CPP) $(CPPFLAGS) -c sweat.cpp

steamboat.o: steamboat.cpp gum.h school.h
	$(CPP) $(CPPFLAGS) -c steamboat.cpp

stair.o: stair.cpp goldfish.h
	$(CPP) $(CPPFLAGS) -c stair.cpp

seen.o: seen.cpp classmate.h
	$(CPP) $(CPPFLAGS) -c seen.cpp

scream.o: scream.cpp hair.h squak.h service.h
	$(CPP) $(CPPFLAGS) -c scream.cpp

reindeer.o: reindeer.cpp service.h goldfish.h sqeak.h
	$(CPP) $(CPPFLAGS) -c reindeer.cpp

if.o: if.cpp service.h raise.h squeak.h
	$(CPP) $(CPPFLAGS) -c if.cpp

hail.o: hail.cpp ncurses.h sqeak.h 
	$(CPP) $(CPPFLAGS) -c hail.cpp

grade.o: grade.cpp goodbye.h
	$(CPP) $(CPPFLAGS) -c grade.cpp

